### PR TITLE
Fixed printing of GAP strings containing null characters (skip them instead of truncating the string)

### LINKED ISSUE #4120: strings that contain null characters
The following happens in released versions of GAP and in the current master branch.
```
gap> s:= "abc\000def";
"abc\000def"
gap> Length( s );
7
gap> Print( s, "\n" );
abc
```
Is this a bug  or a feature?
(In the latter case, it should become documented.)

### PR DESCRIPTION
**Pull request by nskeip**
Fixes #4120.

Print function used to have a problem: if a GAP string contained a null character, then the string was printed only up to the null character (which is an expected behavior for traditional C strings). Now a GAP string conaining a null character would be printed from start to end and the null character would be skipped.

## Text for release notes

See title.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This definately improves things. I notice there are other cases in that function which have the same issue (stopping parsing strings at null), but I'm not sure if those are easy for users to call.

**Comment by james-d-mitchell** [comment]
I think I'd prefer this if the printed output included the \0 character, I.e. so that the output was the same as that of ViewObj but without the ". This'd be less astonishing in my opinion.

**Comment by nskeip** [comment]
> This definately improves things. I notice there are other cases in that function which have the same issue (stopping parsing strings at null), but I'm not sure if those are easy for users to call.

Same thing. Noticed that %G and %S got quite similar logic, but it seems like it's not a problem for the end user.

**Review by ChrisJefferson — APPROVED** [review]

**Comment by ChrisJefferson** [comment]
In terms of priting out \0, I'm not opposed to this, but we already silently swallow many unprintable characters (we just send them for printing, and nothing gets displayed), it's just that `\0` was causing problems as it's treated as end of string.

**Comment by fingolfin** [comment]
Regarding other format specifiers:
- `%S` is not used (anymore), and anyway it takes a zero-terminated string, so no need to worry about that
- `%G` and `%C` *are* used, but only by `gac`, the GAP-to-C-compiler -- each once:
```C
    Emit( "%c = MakeString( \"%C\" );\n", string, str);
...
            Emit( "NameFunc[%d] = MakeImmString(\"%G\");\n", i, n );
```

The latter two are specifically used to sanitize valid GAP strings into a format that can then be re-read by a C compiler... and looking at it, I don't think either is implemented correctly (or alternatively: neither is suitable for what 'gac' uses it). So instead we should probably only retain `%C` (and drop `%G` and `%S`), and fix `%C` to do the right thing in all cases; which is to *either* escape low-value bytes into suitable C escapes (using octal or hex notation?), *or* to reject any of those. 

Assuming we "fix" `%C` to handle any chars, I would look at `SPECIAL_CHARS_VIEW_STRING` in the GAP library to decide how to handle them; and I would add a test to `tst/test-compile` which involves compiling code that involves a string constant as generated by `List([0..255],CHAR_INT);`; and possibly some functions with "evil" names...


Actually there are *more* pitfalls there: one could e.g. define a unary function `function( x\,y ) end` where the single argument has a comment in its name. I am pretty sure that will confuse gac, too, because it uses `ArgStringToList` -- luckily there is a simple fix: don't emit code using `ArgStringToList`, instead emit a combination of `MakeImmString` and `NewPlistFromArgs`.



Anyway, this all goes way beyond this PR. I'll submit a PR of my own addressing some of these.

**Review by fingolfin — APPROVED** [review]

File: src/io.c [hunk 1]
```diff
@@ -1594,43 +1594,48 @@ static inline void FormatOutput(
...
-      for ( Int i = 0; ((const Char *)arg1)[i] != '\0'; i++ ) {
-          const Char* q = ((const Char *)arg1) + i;
-          if (*q == '\\' && IO()->NoSplitLine == 0) {
-              if (*(q + 1) < '8' && *(q + 1) >= '0')
-                  IO()->NoSplitLine = 3;
-              else
-                  IO()->NoSplitLine = 1;
+      for ( Int i = 0; i < len; i++ ) {
+        const Char* q = ((const Char *)arg1) + i;
+        if (*q == '\0') continue;
```
Comment (fingolfin) [inline src/io.c:1630]: If we do this then arguably the computation of 'prec' above is incorrect for strings containing a null byte. But that seems OK to me, it's a border case and if  you print strings with null bytes, things just are weird anyway. But I think we can at least insert a comment to explain
```suggestion
        // skip null bytes; this means 'prec' is off in this case. Fixing this
        // is not worth the effort. So instead, new rule: if you print strings
        // with null bytes, behavior of 'prec' is undefined.
        if (*q == '\0')
          continue;
```
This is still a net improvement over the current behavior

**Comment by fingolfin** [comment]
I've now made PR #5556 motivated by this one here.

File: src/io.c [hunk 2]
```diff
@@ -1594,43 +1594,52 @@ static inline void FormatOutput(
...
       /* must be careful that line breaks don't go inside
          escaped sequences \n or \123 or similar */
-      for ( Int i = 0; ((const Char *)arg1)[i] != '\0'; i++ ) {
-          const Char* q = ((const Char *)arg1) + i;
-          if (*q == '\\' && IO()->NoSplitLine == 0) {
-              if (*(q + 1) < '8' && *(q + 1) >= '0')
-                  IO()->NoSplitLine = 3;
-              else
-                  IO()->NoSplitLine = 1;
+      while (len--) {
```
Comment (fingolfin) [inline src/io.c:1628]: Argh. I had changed this line to this last night (to avoid comparing `Int` with `UInt` values):
```suggestion
      for (UInt i = 0; i < len; i++) {
```
But then this morning I thought "why not simplify it further?" Well because `i` is used in the next line, dummy :joy:

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Thanks, @nskeip !
