### PR TITLE
Catch overflow in header size

### LINKED ISSUE #5508: Very large arrays in functions are parsed incorrectly
Reported by @MathieuDutSik originally.

GAP is silently failing to handle very large arrays in Read. Here is some self-contained code which shows the issue. It might be we decide to not handle this (depending on what is going wrong), but the silent failing is bad.

First I make a huge string, which represents all the integers from 1 to 9000000 (the `List([1..9000000], x -> x)` just forces GAP to explictly build the list, rather than represent as a range).

```strlist := String(List([1..9000000], x -> x));;```

If I use `EvalString`, this has the expected length:

```
gap> l := EvalString(strlist);;
gap> Length(l);
9000000
```

But, if I build a function then `Read` this string, the result produces a much shorter string (if I save the file to disk I get exactly the same output)

gap> func := Concatenation("lf := function() return ", strlist, "; end;");;
gap> Read(InputTextString(func));;
gap> Length(lf());
611392

If I print the string, I can see it stopping early:

```
gap> Print(lf);
.....
        611366, 611367, 611368, 611369, 611370, 611371, 611372, 611373, 611374, 611375, 611376, 611377, 611378, 611379, 611380,
        611381, 611382, 611383, 611384, 611385, 611386, 611387, 611388, 611389, 611390, 611391, 611392 ];
end
```

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Fixes #5508 (GAP produces incorrect code when there are very large arrays inside functions). GAP will silently fail whenever there is a function with 2097152 or more elements given explicitly, inside a function (note a list must be this long, a list of lists whose sublists contain this many elements would be fine).

We could also look at increasing how much allowance we give, but I'm tempted to put this commit in as is (unless there are any small fixes / suggestions), because then if anyone has code that has hit this bug in the past, they will get a clear error message that an error has occurred (in fact, perhaps I should even extend the error to say "this code may have given incorrect answers in previous versions of GAP"?)

### CODE REVIEW

File: src/code.c [hunk 1]
```diff
@@ -259,6 +259,10 @@ Stat NewStatOrExpr(CodeState * cs, UInt type, UInt size, UInt line)
     StatHeader * header = STAT_HEADER(cs, stat);
     header->line = line;
     header->size = size;
+    // check size fits inside header
+    if (header->size != size) {
+        Panic("Function too large");
```
Comment (fingolfin) [inline src/code.c:264]: Why a panic (immediate abort of the process) and not a simple error?

Comment (ChrisJefferson) [reply src/code.c:264]: I put a panic in first, mainly to check I've got the right place.

An error might be OK, but looking at code.c, there aren't currently any errors there, so I wasn't sure what would happen if, inside coding, we caused an error -- is GAP in a fit state to produce an error when part way through coding?

Comment (fingolfin) [reply src/code.c:264]: Yes, calling ErrorQuit is perfectly fine. It might even be able to add a test case exercising that?

Comment (ChrisJefferson) [reply src/code.c:264]: Actually, this was good, as it's easier to test with ErrorQuit. I've added two tests, both to catch maximum list size works, and one larger produces the error.

File: tst/testspecial/func-overflow.g [hunk 2]
```diff
@@ -0,0 +1,3 @@
+strlist := String(List([1..2097152], x -> x));;
+func := Concatenation("lf := function() return ", strlist, "; end;");;
```
Comment (fingolfin) [inline tst/testspecial/func-overflow.g:2]: Why is this in testspecial and not part of the `.tst` file above?
```
gap> strlist := String(List([1..2097152], x -> x));;
gap> func := Concatenation("lf := function() return ", strlist, "; end;");;
gap> Read(InputTextString(func));;
Error, function too large for parser
```
should work fine there, no?

**Review by fingolfin — APPROVED** [review]
Just to say, despite my nitpicking, this is of course a good PR fixing a real issue in a sensible way -- thank you :-)

File: tst/testspecial/func-overflow.g (hunk 2 above)
Comment (ChrisJefferson) [reply tst/testspecial/func-overflow.g]: The reason this was here is previously when this PRed "panic"ed, I couldn't do that in a normal test. Now it's an error, I can (I also added a record test as well. I don't know if anyone would ever create such a huge record in code, but it doesn't hurt to catch it!)

File: tst/testinstall/function.tst [hunk 3]
```diff
@@ -339,5 +339,29 @@ function ( x ) return ([ [ x ] ]{[ 1 ]}{[ 1 ]})[1, 1]; end
...
+gap> Read(InputTextString(funcstr));;
+gap> func() = [1..2097151];
+true
+gap> funcstr := String(List([1..2097152], x -> x));;
+gap> funcstr := Concatenation("func := function() return ", funcstr, "; end;");;
+gap> Read(InputTextString(funcstr));;
+Error, function too large for parser
+
+# Test functions with very large records
+gap> r := rec();; for x in [1..2097150/2] do r.(x) := x; od;;
```
Comment (fingolfin) [inline tst/testinstall/function.tst:354]: Running the above code changes the behavior of GAP in a way that breaks another test later in the test suite. In a nutshell:
```
gap> r:=rec();
rec(  )
gap> \.(r, 1000000);
Error, Record Element: <rnam> must be a valid rnam (not the integer 1000000)
not in any function at *stdin*:2
type 'quit;' to quit to outer loop
brk>
gap> r2 := rec();; for x in [1..2097150/2] do r2.(x) := x; od;;
gap> \.(r, 1000000);
Error, Record Element: '<rec>.992517' must have an assigned value
not in any function at *stdin*:5
type 'quit;' to quit to outer loop
```


Possible fix: modify `tst/testinstall/recordname.tst` to use, say `MAX_SIZE_LIST_INTERNAL` instead of `1000000`, should fix this...

Comment (fingolfin) [reply tst/testinstall/function.tst:354]: I've adjusted this test now, let's see if that is enough.

File: src/code.c [hunk 4]
```diff
@@ -259,6 +259,10 @@ Stat NewStatOrExpr(CodeState * cs, UInt type, UInt size, UInt line)
     StatHeader * header = STAT_HEADER(cs, stat);
     header->line = line;
     header->size = size;
+    // check size fits inside header
+    if (header->size != size) {
```
Comment (fingolfin) [inline src/code.c:263]: Unfortunately this is not enough in the 32bit case...

**Comment by ChrisJefferson** [comment]
Just wanted to point out this is now updated (just fixed tests for 32-bit GAP).

File: src/code.c (hunk 4 above)
Comment (ChrisJefferson) [reply src/code.c:263]: I think this was OK for 32-bits, just the test needing fixing (as 32-bit objects are smaller, we fit more in the allowed size)

Comment (fingolfin) [reply src/code.c:263]: makes sense!
