### PR TITLE
Forbid 3 argument Add for atomic lists

### LINKED ISSUE #1918: HPC-GAP: 3-argument version of Add for atomic lists is broken
Consider this:
```
gap> l:=[1,2,3];;
gap> Add(l,4,1); l;
[ 4, 1, 2, 3 ]
```
versus this:
gap> l:=AtomicList([1,2,3]);;
gap> Add(l, 4); l;
[ 1, 2, 3, 4 ]
```

I understand that inserting an element in the middle of an atomic list makes little sense. But then it should give an error, instead of doing something else.

The cause of this is in `FuncADD_LIST3`, which contains this code:
```C
...
  if ( IS_PLIST( list ) ) {
    AddPlist3( list, obj, ipos );
  } else if ( TNUM_OBJ( list ) < FIRST_EXTERNAL_TNUM ) {
    AddList3( list, obj, ipos );
#ifdef HPCGAP
  } else if ( TNUM_OBJ(list) == T_ALIST ) {
    AddAList( list, obj );
#endif
...
```
As you can see, in the atomic list case, `ipos` is simply ignored.

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This fixes #1918, by forbidding 3 argument Add on atomic lists.

This is (slightly) non-trivial, because we still want 2-argument Add to work, and we implement 2 argument add by calling 3-argument add and passing (Obj)0.

### CODE REVIEW

File: src/listfunc.c [hunk 1]
```diff
@@ -160,7 +160,8 @@ Obj FuncADD_LIST3 (
   } else if ( TNUM_OBJ( list ) < FIRST_EXTERNAL_TNUM ) {
     AddList3( list, obj, ipos );
 #ifdef HPCGAP
-  } else if ( TNUM_OBJ(list) == T_ALIST ) {
+  // Only support adding to end of atomic lists
+  } else if ( TNUM_OBJ(list) == T_ALIST && pos == (Obj)0 ) {
     AddAList( list, obj );
```
Comment (fingolfin) [inline src/listfunc.c]: This fix is of course correct, but do we really want to fall-through to regular method dispatch? The alternative would be to move the check for `pos == 0` inside this `else if`, and if `pos != 0`, then we directly call `ErrorMayQuit` with a message like "Inserting elements at a specific position in an atomic list is not possible" or so.

This would users who run into the problem but don't know what's going on -- they still might not know why this operation is not supported, but now at least they can ask a better question.

Comment (ChrisJefferson) [reply src/listfunc.c]: While I agree in principle, there is a general pattern here, there are a lots of list methods which fixed and variable sized atomic lists don't support, and they all end up in regular method dispatch.
