### PR TITLE
Handle out of memory errors better (variant of PR #3793)

### LINKED ISSUE #3297: GAP terminates session when trying to calculate large coset space
The calculation
```G:=SymmetricGroup(14);
Sym( [ 1 .. 14 ] )
gap> H:=Group((1,2),(2,3));
Group([ (1,2), (2,3) ])
gap> RightCosets(G,H);
```
causes GAP to terminate with the message `gap: cannot extend the workspace any more!` and to delete the history of the current session.

### LINKED ISSUE #3786: System Panic when working with large solvable group
[This was reported by Heiko Dietrich]

### Observed behaviour

    gap> code:= rec( code := 4036976711286048149259,
    >                extdim := [  ], isFrattiniFree := true,
    >                isUnique := true,
    >             order := 4037839681938311097109 );
    gap> F := PcGroupCodeRec( code );
    <pc group of size 4037839681938311097109 with 2 generators>
    gap> Factors(4037839681938311097109);
    [ 4679, 862970652262943171 ]
    gap> IrreducibleModules(F,GF(4679),1);
     #G  FULL  691935/  68330kb live  4606596/ 263344kb dead  Panic in src/sysmem.c:654: cannot extend the workspace any more!

### Expected behaviour

A clearer error message, possibly in break loop

### PR DESCRIPTION
**Pull request by fingolfin**
This is a variant of PR #3793 by @ChrisJefferson , rebased onto PR  #3812, and with several of my remarks on PR #3793 addressed.

Closes #3793
Fixes #3297
Fixes #3786

I am also happy to close this if @ChrisJefferson prefers to update his PR!

### CODE REVIEW

File: src/gasman.c [hunk 1]
```diff
@@ -2270,10 +2270,14 @@ UInt CollectBags (
...
-        if (done == 2)
-            return 0;
 
-        // if we are not done, then try a full collection next
+        // the variable done can take on several values:
+        // 0: not yet finished, try again with a full collection
+        // 1: finished successfully to allocate the request memory
+        // 2: giving up, we are out of memory
+
+        // if there is another iteration of this loop, the we should perform a
```
Comment (ChrisJefferson) [inline src/gasman.c]: the we -> then we (not required)
