### PR TITLE
kernel: add SymbolTable type, change GetInputFilenameID to use it

### LINKED ISSUE #4771: Performance regression
In PR #2585 I attempted to rewrite `EvalString` in a "cleaner" fashion. Back then this was rejected because it was reported to slow down things by a factor of three. Today I discussed this approach with @laurentbartholdi (he suggested the same refactoring of the code independently), which lead me to reexamine the performance issue... And I think we have a performance regression here.

So here is my test code, comparing "old" and "new" `EvalString` implementation:
```gap
myeval := function( s )
  local a, f;
  # Prepend 'return' and append ';' to the given string; also add newlines to
  # ensure that if there are syntax errors in the evaluated string, GAP
  # prints only the evaluated string, but not the 'return' and ';' we prepend
  # resp. append.
  a := "return\n";
  Append(a, s);
  Append(a, ";\n");
  f := ReadAsFunction(InputTextString(a));
  return f();
end;;
for i in [1..100000] do EvalString("12+13"); od; time;
for i in [1..100000] do myeval("12+13"); od; time;
```

Some timings done on my MacBok Pro 14" with M1 CPU:
```
# GAP master
gap> for i in [1..100000] do EvalString("12+13"); od; time;
572
gap> for i in [1..100000] do myeval("12+13"); od; time;
552

# GAP 4.11.1
gap> for i in [1..100000] do EvalString("12+13"); od; time;
360
gap> for i in [1..100000] do myeval("12+13"); od; time;
338

# GAP 4.10.2
gap> for i in [1..100000] do EvalString("12+13"); od; time;
128
gap> for i in [1..100000] do myeval("12+13"); od; time;
448

# GAP 4.9.3
gap> for i in [1..100000] do EvalString("12+13"); od; time;
125
gap> for i in [1..100000] do myeval("12+13"); od; time;
327

# GAP 4.8
for i in [1..100000] do EvalString("12+13"); od; time;
83
for i in [1..100000] do myeval("12+13"); od; time;
96
```
So when looking at GAP 4.9 or 4.10, one really sees a factor of 2.5 - 3.5. But in GAP master and in GAP 4.8 both methods are about the same speed -- except GAP 4.8 is faster by a factor of ~5.5...

After some more experimenting, I noticed the following: if I run the second loop multiple times in GAP 4.8, it gets slower, until it stabilizes at about ~350 (which is about the same as in GAP 4.11); even if I force a garbage collection. This is really strange:
```
gap> GASMAN("collect"); for i in [1..100000] do myeval("12+13"); od; time;
324
gap> GASMAN("collect"); for i in [1..100000] do myeval("12+13"); od; time;
323
gap> GASMAN("collect"); for i in [1..100000] do myeval("12+13"); od; time;
377
gap> GASMAN("collect"); for i in [1..100000] do myeval("12+13"); od; time;
343
gap> GASMAN("collect"); for i in [1..100000] do myeval("12+13"); od; time;
347
```
No such slowdown happened for `EvalString`.

### PR DESCRIPTION
**Pull request by fingolfin**
- kernel: get rid of RNamNameWithLen
- kernel: add a dedicated SymbolTable type
- kernel: switch GetInputFilenameID to use a SymbolTable

Resolves #4771 (mostly, at least...?)

Needs some cleanup, but overall seems to work. Using the test function from #4771, and together with PR #4772, I now get the following:
```
gap> for i in [1..100000] do EvalString("12+13"); od; time;
125
gap> for i in [1..100000] do myeval("12+13"); od; time;
119
```

Granted, this is still slower than GAP 4.8, but only by a factor of about 1.5, not 5.5.

### CODE REVIEW

**Comment by fingolfin** [comment]
Regarding performance impact on `GVarName` and `RNamName`: they both now use the new `LookupSymbol` helper. To allow this to be generic, it uses a callback `symtab->nameFunc` to map symbol ids back to symbol strings. So this requires a jump to a function pointer, which usually just amounts to an `ELM_PLIST` invocation. Whereas in the old code, we directly used `ELM_PLIST`, inlined and all. So I was a bit vary about a performance impact.

But it turns out there isn't really one, at least not according to this incredibly sophisticated test:
```
gap> str:="dfsdfdsf";;GASMAN("collect"); for i in [1..1000000] do RNamObj(str); od; time;
31
gap> str:="dfsdfdsf";;GASMAN("collect"); for i in [1..1000000] do RNamObj(str); od; time;
34
gap> str:="dfsdfdsf";;GASMAN("collect"); for i in [1..1000000] do RNamObj(str); od; time;
33

# the first iteration below generates tons of hash table entries, so its slower than
# the repetitions
gap> GASMAN("collect"); for i in [1..1000000] do RNamObj(i); od; time;
199
gap> GASMAN("collect"); for i in [1..1000000] do RNamObj(i); od; time;
59
gap> GASMAN("collect"); for i in [1..1000000] do RNamObj(i); od; time;
60
```

I am only going to paste one, because the results for master and this PR are basically indistinguishable, they both look like that (with the usual fluctuations).

File: src/gvars.c [hunk 1]
```diff
@@ -107,46 +109,6 @@ static Obj * PtrGVars;
...
-static pthread_rwlock_t GVarLock;
-static void *GVarLockOwner;
-static UInt GVarLockDepth;
-
-static void LockGVars(int write) {
-  if (PreThreadCreation)
-    return;
-  if (GVarLockOwner == GetTLS()) {
-    GVarLockDepth++;
-    return;
```
Comment (fingolfin) [inline src/gvars.c:127]: Note that this old locking code allowed for recursive locking when called from the same thread.

I thought this was irrelevant, as I saw no way this could ever be needed.

Alas, it is, as `UpdateCopyFopyInfo` also takes that lock, and it then calls `DeclareAllGVars` while holding the lock, and *that* calls `GVarName`.... *sigh*. I think at this point it's best to just excise the complete `GVarDescriptor` code; almost nothing really uses it anyway. I'll look into that.

Comment (fingolfin) [reply src/gvars.c:127]: *sigh* it's not quite as simple. And I don't want to accidentally break HPC-GAP even more (though perhaps I should just give up on that pipe dream *double sigh*).

So, I guess I'll have to replicate the recursive locking ability

**Review by ChrisJefferson — APPROVED** [review]
