### PR TITLE
Fix printing of nested logical operators

### LINKED ISSUE #4449: Printing a function with nested equalities yields unparsable code
Consider the following code:
```
Print(x -> (x = x) = true);
```

### Observed behaviour

It prints
```
function ( x )
    return x = x = true;
end
```
which is not parsable GAP code.

### Expected behaviour

It should print
```
function ( x )
    return (x = x) = true;
end
```

### Copy and paste GAP banner (to tell us about your setup)
```
 *********   GAP 4.12dev built on 2021-04-29 23:34:25-0400
 *  GAP  *   https://www.gap-system.org
 *********   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, AutPGrp 1.10.2, Browse 1.8.11, CaratInterface 2.3.3, CRISP 1.4.5, Cryst 4.1.23, 
             CrystCat 1.1.9, CTblLib 1.3.1, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.4, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4.1, LAGUNA 3.9.3, 
             orb 4.8.3, Polenta 1.3.9, Polycyclic 2.15.1, PrimGrp 3.4.1, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, SmallGrp 1.4.2, Sophus 1.24, 
             SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.0, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

### Notes
```
Print(x -> true = (x = x));
```
correctly prints
```
function ( x )
    return true = (x = x);
end
```
so I assume the required code already exists and simply has to be extended to the first case.

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Fixes #4449

### CODE REVIEW

File: src/exprs.c [hunk 1]
```diff
@@ -1331,6 +1331,7 @@ static void PrintBinop(Expr expr)
 {
     UInt                oldPrec;        /* old precedence level           */
     const Char *        op;             /* operand                         */
+    Int                 printEqPrec = 0; /* Print () at equal precedence   */
```
Comment (fingolfin) [inline src/exprs.c:1334]:
```suggestion
    BOOL                printEqPrec = FALSE; /* Print() at equal precedence */
```

File: src/exprs.c [hunk 2]
```diff
@@ -1353,9 +1354,16 @@ static void PrintBinop(Expr expr)
     case EXPR_POW:    op = "^";    PrintPrecedence = 16;  break;
     default:       op = "<bogus-operator>";   break;
     }
+    // The logical operators (=|<>|<|>|<=|>=|in) need brackets at
+    // equal precedence level
+    if (PrintPrecedence == 8) {
+        printEqPrec = 1;
```
Comment (fingolfin) [inline src/exprs.c:1360]:
```suggestion
        printEqPrec = TRUE;
```

**Review by fingolfin — APPROVED** [review]

**Comment by ChrisJefferson** [comment]
Thanks, changes made
