### PR TITLE
Ensure all lists of lists are marked as rectangular tables when approriate

### LINKED ISSUE #5449: IsRectangularTable not correctly recognized by a method selector
### Commentary
It appears that a list consisting of strings of the same length is recognized as IsRectangularTable but is not picked up by a method selector with that filter.

### Observed behaviour
```
gap> DeclareOperation( "AcceptTable", [ IsRectangularTable ] );
gap> InstallMethod( AcceptTable, "for rectangular table", [ IsRectangularTable ], t -> true );
gap> t := [ "ab", "ba" ];;
gap> IsRectangularTable( t );
true
gap> AcceptTable( t );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `AcceptTable' on 1 arguments at /opt/gap-4.12.2/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:6
type 'quit;' to quit to outer loop
```

### Expected behaviour
the last command should return true

### Copy and paste GAP banner (to tell us about your setup)
```

 ┌───────┐   GAP 4.12.2 of 2022-12-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, CaratInterface 2.3.4, CRISP 1.4.6, Cryst 4.1.25,
             CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.9, GAPDoc 1.6.6, genss 1.6.8,
             IO 4.8.0, IRREDSOL 1.4.4, LAGUNA 3.9.5, orb 4.9.0, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.3,
             RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, SmallGrp 1.5.1, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9,
             TransGrp 3.6.3, utils 0.81
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Fixes #5449

Basically, we were inconsistent on if we treated lists of lists as if they were rectangular tables, depending on what type the inner lists were.

I have tried to very carefully write the code so in the standard cases where everything is a plist of plist, or a plist of not lists, the code is exactly as fast as it used to be -- I tried benchmarking this and I couldn't measure any differences.

### CODE REVIEW

File: src/plist.c [hunk 1]
```diff
@@ -287,20 +287,22 @@ static Int KTNumPlist(Obj list, Obj * famfirst)
...
+        // if entry is a homogeneous list this might be a table or list
+        if (ktnumFirst >= T_PLIST_HOM) {
+            isTable = 1;
+            isRect = 1;
+            len = LEN_PLIST(elm);
+        }
+        else if (ktnumFirst == 0 && IS_HOMOG_LIST(elm)) {
+            isTable = 1;
+            // Only handle small lists as rectangular
+            if(IS_SMALL_LIST(elm)) {
```
Comment (fingolfin) [inline src/plist.c:300]:
```suggestion
            if (IS_SMALL_LIST(elm)) {
```

File: src/plist.c [hunk 2]
```diff
@@ -287,20 +287,22 @@ static Int KTNumPlist(Obj list, Obj * famfirst)
...
-            {
+        // if entry is a homogeneous list this might be a table or list
+        if (ktnumFirst >= T_PLIST_HOM) {
+            isTable = 1;
+            isRect = 1;
+            len = LEN_PLIST(elm);
+        }
+        else if (ktnumFirst == 0 && IS_HOMOG_LIST(elm)) {
+            isTable = 1;
+            // Only handle small lists as rectangular
```
Comment (fingolfin) [inline src/plist.c:299]:
```suggestion
            // only handle small lists as rectangular
```
for consistency

File: src/plist.c [hunk 3]
```diff
@@ -342,16 +344,21 @@ static Int KTNumPlist(Obj list, Obj * famfirst)
                     isRect = 0;
                 }
                 if ( isTable ) {
-                    // IS_PLIST first, as it is much cheaper
-                    if (!(IS_PLIST(elm) || IS_LIST(elm))) {
-                        isTable = 0;
-                        isRect = 0;
+                    // Check IS_PLIST first, as it is much cheaper
```
Comment (fingolfin) [inline src/plist.c:347]:
```suggestion
                    // check IS_PLIST first, as it is much cheaper
```
for consistency

**Review by fingolfin — APPROVED** [review]
Overall seems sensible to me

**Comment by fingolfin** [comment]
@ChrisJefferson will you update this?
