### PR TITLE
kernel: fix GC crash in PushValue()

### LINKED ISSUE #3187: Segfault in tst/testinstall/syntaxtree.tst
This happens in the master branch when all packages are loaded. See e.g. on Travis here: https://travis-ci.org/gap-infra/gap-docker-master-testsuite/jobs/480427212. Started to happen two days ago.

### PR DESCRIPTION
**Pull request by fingolfin**
The NEW_PLIST call could trigger a GC, which then rendered the value of header
invalid, possibly leading to arbitrary memory corruption, and also the values
pointer of the function body was then not set correctly.

Fixes #3187

### CODE REVIEW

File: src/code.c [hunk 1]
```diff
@@ -516,10 +516,10 @@ void PushBinaryOp (
 */
 static Int PushValue(Obj val)
 {
-    BodyHeader * header = (BodyHeader *)STATE(PtrBody);
-    if (!header->values)
-        header->values = NEW_PLIST(T_PLIST, 4);
-    return PushPlist(header->values, val);
+    Obj values = ((BodyHeader *)STATE(PtrBody))->values;
+    if (!values)
+        values = ((BodyHeader *)STATE(PtrBody))->values = NEW_PLIST(T_PLIST, 4);
```
Comment (ChrisJefferson) [inline src/code.c]: This line looks too clever to me (doing two assignments), also isn't PtrBody a raw pointer, so it's important if GAP calls STATE(PtrBody) before or after the RHS?

Maybe assign to `values` in this line, then assign to PtrBody in a new second line?

Comment (fingolfin) [reply src/code.c]: You're absolutely right. Patch revised.
