### PR TITLE
Fix missing filenames of statements

### LINKED ISSUE #5454: Segfault when triggering an error inside a function created from a syntax tree
Executing the following code gives a segfault:

```
func := function ( )
    Error( );
end;

func := SYNTAX_TREE_CODE( SYNTAX_TREE( func ) );

func( );
```

Tested with GAP 4.12.1 and GAP master. I guess this is related to functions created from syntax trees not having location information, similar to #4508.

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Fixes #5454 (and I looked for similar bugs).

I did wonder if it was better adding the check inside GET_FILENAME_BODY or check the return value for NULL -- for a function used in so few places, I don't think it deeply matters.

### CODE REVIEW

File: src/error.c [hunk 1]
```diff
@@ -160,6 +160,9 @@ static Obj FuncCURRENT_STATEMENT_LOCATION(Obj self, Obj context)
         (FIRST_EXPR_TNUM <= type && type <= LAST_EXPR_TNUM)) {
         Int line = LINE_STAT(call);
         Obj filename = GET_FILENAME_BODY(body);
+        if (!filename) {
+            filename = MakeImmString("<no filename>");
+        }
```
Comment (fingolfin) [inline src/error.c:165]: Wouldn't it make more sense to check `filename` a few line above and then `return Fail;` as in all the other cases in this function that deal with missing location information?

File: src/error.c [hunk 2]
```diff
@@ -208,6 +211,10 @@ static Obj FuncPRINT_CURRENT_STATEMENT(Obj self, Obj stream, Obj context)
 
             Int type = TNUM_STAT(call);
             Obj filename = GET_FILENAME_BODY(body);
+            if (!filename) {
+                filename = MakeImmString("<no filename>");
+            }
```
Comment (fingolfin) [inline src/error.c:216]: But the line the also will be bogus. I would suggest to instead change the `else {` above to `else if (filename != 0) {` (and then of course declare and init `filename` earlier)

**Review by fingolfin — APPROVED** [review]

**Comment by zickgraf** [comment]
Thanks for the fix!
