### PR TITLE
Compare tty identity using fstat, not ttyname (and remove one embarrassing nonsense usage of ttyname)

### LINKED ISSUE #998: kernel: incorrect use of ttyname()
The following is inspired by an issue from our old private tracker, namely <http://tracker.gap-system.org/issues/474>

Currently, `src/system.c` contains this code (twice, actually, with minor differences):
```
    if ( isatty( fileno(stdin) ) && ttyname(fileno(stdin)) != NULL ) {
        if ( isatty( fileno(stdout) ) && ttyname(fileno(stdout)) != NULL
          && ! strcmp( ttyname(fileno(stdin)), ttyname(fileno(stdout)) ) )
```
The problem with that is that `ttyname` may (and, according to its documenation on BSD systems, *does*) return a pointer to an internal static buffer. Hence, comparing the results of two subsequent calls to it will always succeed. 

To fix this, we could store the results of the first invocation in a buffer, and compare then.

However, I am not completely sure what that code is meant to achieve, and how to properly test it, so I am reluctant to make that change myself for now.

### PR DESCRIPTION
**Pull request by fingolfin**
On many (most? all?) POSIX compliant systems, `strcmp( ttyname(fileno(stdin)), ttyname(fileno(stderr)) )` will always return 0, as `ttyname` returns a pointer to a fixed buffer, so we
end up always comparing a string against itself.

Instead, use `fstat` to compare whether the stdin/stdout/stderr reference the same terminals or not: the POSIX standard guarantees that st_dev and st_ino uniquely identify any device.

Also add some comments that explain what is going on in that code in the first place.

Note that this also drops a configure check for `ttyname`, as I think this is available on all systems we support. If not, we can add it back, but then use it more fine-grained -- previously, we completely failed to initialize `syBuf[0]` to `syBuf[3]` if `ttyname` was missing, so I am guessing GAP was broken on such systems anyway.

Also note that we are now always using `fstat`, and in one other place we use `fstat`, there is a comment saying "fstat seems completely broken under CYGWIN", added by @frankluebeck  in 2002. But I am not sure why exactly, resp. what about it is broken. I am hoping that even if it is broken in some way, it won't affect us here... AppVeyor will tell us, I guess.

Fixes #998

### CODE REVIEW

File: src/iostream.c [hunk 1]
```diff
@@ -211,7 +211,6 @@ static UInt OpenPty(int * master, int * slave)
         goto error;
     }
 
-    ttyname = ;
```
Comment (ChrisJefferson) [inline src/iostream.c]: What's going on here? Is this valid C? Is this ever compiled?

Comment (fingolfin) [reply src/iostream.c]: The code was invalid, so nobody used it since I introduced it in April (in commit 138fc2b9c40ded7b88404cd39bee496ce1ff8662 but I am not sure how exactly this mixup happened. Ah well :-/).

One reason to keep this code is that the code *do* use on Linux, *BSD, OSX & Cygwin uses `openpty`, which is not part of POSIX; while this alternate code path is using only POSIX APIs. So it's arguably more portable. Of course we might not care about supporting other UNIX like operating systems. One may also rightfully argue that it's better to remove this dead code and wait for somebody to complain, and then add it back (but this time with an actual use case). I am all open for that.

Personally, I'd prefer to do this in a later PR, instead of delaying this one.
