### PR TITLE
Check supported warnings in configure, fix tons of warnings, enable more warnings

### LINKED ISSUE #1346: Unconditionally using compiler warning flags causes gcc 4.3.4 compile failure
On a supercomputer I am allowed to use compilation stops:
````
DEBRECEN[service0] ~/bin/gap (0)$ make
   C       src/ariths.c => obj/ariths.lo
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough"
cc1: error: unrecognized command line option "-Wno-unknown-warning-option"
make: *** [obj/ariths.lo] Error 1
DEBRECEN[service0] ~/bin/gap (2)$ cc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux) 
DEBRECEN[service0] ~/bin/gap (2)$ 
````
The number in parentheses in the prompt is supposed to show the error code (2 in this case).

Could this be because of #1339?

### PR DESCRIPTION
**Pull request by fingolfin**
This builds on PR #1489 (which should be merged first).

Resolves #1346 (well, I hope, please give it a try).

### CODE REVIEW

File: src/gap.c [hunk 1]
```diff
@@ -791,6 +791,7 @@ Obj FuncWindowCmd (
   Int             n,  m;
   Int             i;
   Char *          ptr;
+  const Char *    inptr;
   Char *          qtr;
```
Comment (ChrisJefferson) [inline src/gap.c]: Was there any reason/need to constify this? Looks like `SyWinCmd` returns a `Char*` anyway.

I only ask because this function doesn't seem to ever be called by anything I can see, so I'd be tempted to not touch it unless we have to (or of course remove it or test it..)

File: src/hpc/atomic.h [hunk 2]
```diff
@@ -13,6 +13,7 @@
 #else
 
 #ifndef WARD_ENABLED
+#define AO_AO_TS_T 0    // HACK
```
Comment (ChrisJefferson) [inline src/hpc/atomic.h]: Could you atleast comment what this 'hack' is for? my googling skills find nothing.

File: src/gap.c (hunk 1 above)
Comment (fingolfin) [inline src/gap.c]: It used to return `Char *`, but this PR makes it return a `const Char *`. This is in turn needed because it returns pointers to string constants.

File: src/hpc/atomic.h (hunk 2 above)
Comment (fingolfin) [inline src/hpc/atomic.h]: Ah, indeed, there should be a comment here -- I forgot about this, my bad. I'll update the PR, but to add it here quickly: This was meant to silence `-Wundef` warnings in libatomic_ops. But this is actually problematic, because it will cause issues on some non-x86 architectures like ARM.

I could instead patch our copy of libatomic. We'd then get the warnings again once we add support for using stock versions of libatomic_ops... but I guess that's acceptable (and we can revisit the issue then)...

I guess I could also try something like:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wundef"
#include <atomic_ops.h>
#pragma GCC diagnostic pop
```
And something similar for clang.. Hum
