### PR TITLE
Make prompt same length as maximum line

### LINKED ISSUE #1235: Segfault when displaying a 128x128 FFE matrix
With latest master, the following command segfaults for me on Mac OS X 10.11.6:
```gap
Display(DiagonalMat(ListWithIdenticalEntries(128,Z(2^2))));
```
However, it works fine on an Ubuntu box. Also, I cannot reproduce it inside lldb (presumably because running GAP in lldb causes GAP to think my terminal is 80x25, but it actually is 270x80.

Indeed, if I shrink my terminal to 180x80 or 230x40, no segfault. But it *does* segfault for e.g. 270x40. Also no segfault at 264x80 and 265x80, but at 266x80 it does segfault again. This sounds to me like there is perhaps a buffer overflow somewhere?

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This partly fixes #1235, which involves too long lines.

This patch doesn't completely look at all parts of this issue, but it does handle all known crashes (the one in #1235, and another one I came across today, printing records when `ScreenSize` is set to 1000).

### CODE REVIEW

File: src/sysfiles.c [hunk 1]
```diff
@@ -1325,7 +1325,7 @@ void syEchos (
 **  'SyFputs' is called to put the  <line>  to the file identified  by <fid>.
 */
 UInt   syNrchar;                        /* nr of chars already on the line */
-Char   syPrompt [256];                  /* characters already on the line   */
+Char   syPrompt [MAXLENOUTPUTLINE];     /* characters already on the line  */
```
Comment (fingolfin) [inline src/sysfiles.c]: So `MAXLENOUTPUTLINE` is 4096 it seems.  Yet in other places, we limit the line length to 32768 (see discussion on #1235) ?

So I am wondering: Does this really resolve those crashes, or just the ones for which we have reproductions? (I.e. did you work through the code logic to verify this eliminates the crash, or does it "just" happen to help in the tested cases?)

Don't get me wrong, I am still fine merging this, I just want to understand how far this really goes :-)

**Comment by ChrisJefferson** [comment]
I'm 95% sure this is two different types of "lines". The one I am fixing refers to a 'screen line', that is a line of output we will display in the terminal. The bigger 32768 refers to an internal line, which we scroll back and forth on the screen, and can be much longer.

This seems to fix all issues to do with us displaying lines on wide terminals (well, terminals up to 4096). Of course, you can still write a much longer line, and I don't know what happens when that gets up to 32,000 characters. Also, limiting that number down to 4096 could, I think, in principle cause problems if anyone is cutting and pasting some auto-generated file with lines longer than 4k (which sounds just about possible).
