### PR TITLE
Julia GC: fix stack marking

### LINKED ISSUE #3114: Error when computing irreducibles of a permutation group
The following happens in GAP 4.10.0 as well as in the current master branch.

```
gap> g:= AtlasGroup( "U3(8).3^2" );;
gap> Irr( g );;
Error, List Element: <list>[19] must have an assigned value in
  M[s][t] := M[s][t] + T[2][i]; at /.../ctblgrp.gi:1790 called from
D.ClassMatrixColumn( D, M, bestMat, col
 ); at /.../ctblgrp.gi:716 called from
SplitStep( D, bsm ); at /.../ctblgrp.gi:2065 called from
DixonSplit( D ) at /.../ctblgrp.gi:2171 called from
IrrDixonSchneider( G, rec(
     ) ) at /.../ctblgrp.gi:2152 called from
IrrDixonSchneider( G ) at /.../ctblgrp.gi:2194 called from
...  at *stdin*:2
type 'quit;' to quit to outer loop
```

(The error messages are not exactly the same in the two versions,
in the sense that they point to different positions in `<list>`.)

GAP 4.9.0 does not have this problem.
The same holds for GAP 4.7.6.
(And the computation in GAP 4.9.0 is much faster than that in GAP 4.7.6.)

### PR DESCRIPTION
**Pull request by rbehrends**
This pull request fixes two separate bugs, related to https://github.com/gap-system/gap/issues/3114.

1. The processor stack was not being marked correctly, as Julia
   made wrong assumptions about the end of the processor stack;
   we now use the value of `stack_bottom` that is being supplied
   to `InitBags()`.
2. `CHANGED_BAG()` was not being called on `CurrLVars` when a collection
   was initiated, unlike for the GASMAN implementation, where this
   happens in `VarsBeforeCollectBags()`.

Fixes #3114

### CODE REVIEW

File: src/julia_gc.c [hunk 1]
```diff
@@ -589,6 +593,13 @@ static void PreGCHook(int full)
     // a thread-local variable.
     SaveTLS = JuliaTLS;
     JuliaTLS = jl_get_ptls_states();
+    // This is the same code as in VarsBeforeCollectBags() for GASMAN.
+    // It is necessary because ASS_LVAR() and related functionality
+    // does not call CHANGED_BAG() for performance reasons. CHANGED_BAG()
+    // is only called when the current lvars bag is being changed. Thus,
+    // we have to add a write barrier at the start of the GC, too.
+    if (STATE(CurrLVars))
+        CHANGED_BAG(STATE(CurrLVars));
```
Comment (fingolfin) [inline src/julia_gc.c]: It's OK to have this in here for now, to get a quick fix; but on the long run, I prefer to fix this properly, by providing a generic "pre-gc hook" in both GASMAN (which already has one) and Julia GC, and then setting that to `VarsBeforeCollectBags`. Also, this "optimization" for lvars needs to be documented in a better place. But neither of these are change request for this PR; me or somebody else can take care of it in a future PR.

File: src/julia_gc.c [hunk 2]
```diff
@@ -527,6 +528,9 @@ void GapRootScanner(int full)
     // current_task != root_task.
     char * stackend = (char *)jl_task_stack_buffer(task, &size, &tid);
     stackend += size;
+    if (JuliaTLS->tid == 0 && JuliaTLS->root_task == task) {
+        stackend = (char *)GapStackBottom;
```
Comment (fingolfin) [inline src/julia_gc.c]: Hmm, but note that this only will work right if GAP is the main process, loading Julia later. If, however, one is starting Julia and from there loading GAP, then `GapStackBottom ` may not be at the base of the stack frame.

This is closely related to (part of) the discussion on issue #3089 ;  see also PR #3096

File: src/julia_gc.c [hunk 3]
```diff
@@ -545,7 +549,7 @@ void GapRootScanner(int full)
     for (Int i = 0; i < GlobalCount; i++) {
         Bag p = *GlobalAddr[i];
         if (IS_BAG_REF(p)) {
-            JMark(p);
+            TryMark(p);
```
[the remark this answers is not in the document]
Comment (rbehrends) [reply src/julia_gc.c]: Oops, that's actually a leftover from debugging and should be removed. I'll get rid of it.

File: src/julia_gc.c (hunk 1 above)
Comment (rbehrends) [reply src/julia_gc.c]: I agree. My goal here was to get the fix out ASAP. As the code is identical to `VarsBeforeCollectBags()`, this should be unified.

File: src/julia_gc.c (hunk 2 above)
Comment (rbehrends) [reply src/julia_gc.c]: Yes, and `GapTaskScanner()` may also need an update. That said, it should properly be handled so that Julia gets to know the proper end of the stack for task switching.

**Comment by fingolfin** [comment]
I can confirm that this fixes #3114 for me; I hope @ThomasBreuer can confirm that as well (and then check which of the other crashes he was getting are also fixed; hopefully all.... ;-)

File: src/julia_gc.c (hunk 2 above)
Comment (embray) [reply src/julia_gc.c]: ISTM there needs to be a `SetStackBottomBags` (as in #3096) for Julia GC as well.

Comment (fingolfin) [reply src/julia_gc.c]: Possible, but this code is very much in flux, so it doesn't really matter at this stage.

**Comment by fingolfin** [comment]
Backported to stable-4.10 in af3bb41d34326ec2771ef71f1738a81c88cfab85
