### PR TITLE
Speed up RootMod and RootsMod for moduli with large prime factors; also add `IS_PROBAB_PRIME_INT` kernel function

### LINKED ISSUE #758: RootMod on newer versions of gap
I was teaching `RootMod` in the computer classroom and an student came to me with the following example. He was puzzled that for the first time (Miller-Rabin and other stuff) his own implementation was faster than that of GAP.

```
c := 87665785060273447596735547586847436354365986897267;
d := 5676193656034756392656593936564928264920283748503726385950382638505826243749593626948538293405737101;
gap> RootMod(c,d);time;
fail
69688
```

The above example was executed in noether (St. Andrews, with GAP 4.8.1). If you execute it twice, then it takes nothing. Even if you change c to get a positve answer

```
gap> c := 87665785060273447596735547586847436354365986897267+12;
87665785060273447596735547586847436354365986897279
gap> RootMod(c,d);time;
277281960068688920231110666322684535614170829118408321537065593309824476399230514\
2689466354417560800
0
```

In my old laptop with GAP Version 4.7.4, the output takes 0 milliseconds, even in the first call. So the problem seems to reproduce in newer versions of GAP.

I wonder if RootMod is checking if d is (psedo)prime, and if Jacobi(c,d)=1 or not. Is the newer version loading something the first time `RootMod` is called? Am I doing something wrong?

Thanks,
Pedro

### PR DESCRIPTION
**Pull request by fingolfin**
For RootMod and RootsMod, all computations are eventually reduced to
prime moduli. This means we have to factor the initial modulus, which
can be very expensive. However, it actually suffices if the factors are
Fermat pseudo primes relative to certain bases... So we switch to using
the UseProbabilisticPrimalityTest option, and add a test which verifies
the required property n^(p-1) = 1 (mod p) where necessary. If this
fails, we could do something clever to recover, but instead, we simply
print an error message requesting that the user reports it to use; for
if it happens, then either there is a bug (which we should fix), or else
we found a BPSW pseudo prime that is not a prime, and this is something
we definitely would want to know about (and publish, too ;-).

Fixes #758

This PR also adds `IS_PROBAB_PRIME_INT`, which calls the GMP function `mpz_probab_prime_p`.

### CODE REVIEW

File: src/gmpints.c [hunk 1]
```diff
@@ -2176,6 +2176,42 @@ Obj FuncPOWERMODINT ( Obj self, Obj base, Obj exp, Obj mod )
...
+}
+
+/****************************************************************************
+**
+*/
+Obj FuncIS_PROBAB_PRIME_INT ( Obj self, Obj n, Obj reps )
+{
+  REQUIRE_INT_ARG( "IsProbablyPrimeInt", "n", n );
+  REQUIRE_INT_ARG( "IsProbablyPrimeInt", "reps", reps );
+  if ( ! IS_INTOBJ(reps) )
```
Comment (ChrisJefferson) [inline src/gmpints.c]: While not required for this patch, I think a `REQUIRE_SMALL_INT_ARG` might be a nice addition.

**Comment by hulpke** [comment]
Very nice!

**Comment by fingolfin** [comment]
I'll rebase this once PR #1178 has been merged.

**Comment by alex-konovalov** [comment]
Shall we merge this?
