### PR TITLE
Encode if we have readline in workspaces

### LINKED ISSUE #1079: Segfault loading workspace wo readline support
I compiled GAP 4.8.6 wo readline support, saved a workspace, then recompiled GAP 4.8.6 with readline support. Starting GAP then yields a segfault. For a full run see below, the error is basically
```GAP
Error, Record: '<rec>.CommandLineEditFunctions' must have an assigned value in
  SHELL( GetBottomLVars(  ), false, false, 3, true, prompt, function (  )
...
```

This could in principle lead to problems if users would want to share or send each other GAP-workspaces. ( Does anybody ever do this? )

### Observed behaviour
Note that the banner says  `Libs used:  gmp` although this GAP version actually uses readline. (Hence the error I guess)
```GAP
 ┌───────┐   GAP 4.8.6, 12-Nov-2016, build of 2017-01-12 17:56:36 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp
 Loaded workspace: /home/sergio/.gap/emptyWorkspace
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, 
             GAPDoc 1.5.1, IRREDSOL 1.3.1, LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, RadiRoot 2.7, ResClasses 4.5.0, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> Error, Record: '<rec>.CommandLineEditFunctions' must have an assigned value in
  SHELL( GetBottomLVars(  ), false, false, 3, true, prompt, function (  )                                                                                     
      if IsBound( OnGAPPromptHook) and IsFunction( OnGAPPromptHook )  then                                                                                    
          OnGAPPromptHook(  );                                                                                                                                
      else                                                                                                                                                    
          return;                                                                                                                                             
      fi;                                                                                                                                                     
      return;                                                                                                                                                 
  end, "*stdin*", "*stdout*", true ); at /opt/gap/gap4r8/lib/session.g:49 called from                                                                         
SESSION(  ); at /opt/gap/gap4r8/lib/session.g:70 called from                                                                                                  
<function "POST_RESTORE">( <arguments> )                                                                                                                      
 called from read-eval loop at line 1 of *stdin*                                                                                                              
you can 'return;' after assigning a value                                                                                                                     
brk> Error, Record: '<rec>.CommandLineEditFunctions' must have an assigned value in                                                                           
  res := SHELL( context, mayReturnVoid, mayReturnObj, 1, false, prompt, false, "*errin*", "*errout*", false ); at /opt/gap/gap4r8/lib/error.g:235 called from 
SHELL( GetBottomLVars(  ), false, false, 3, true, prompt, function (  )                                                                                       
      if IsBound( OnGAPPromptHook) and IsFunction( OnGAPPromptHook )  then                                                                                    
          OnGAPPromptHook(  );                                                                                                                                
      else                                                                                                                                                    
          return;                                                                                                                                             
      fi;                                                                                                                                                     
      return;                                                                                                                                                 
  end, "*stdin*", "*stdout*", true ); at /opt/gap/gap4r8/lib/session.g:49 called from                                                                         
SESSION(  ); at /opt/gap/gap4r8/lib/session.g:70 called from                                                                                                  
<function "POST_RESTORE">( <arguments> )                                                                                                                      
 called from read-eval loop at line 1 of *errin*                                                                                                              
you can 'return;' after assigning a value   
```

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Encode if readline is enabled in workspaces. Fixes #1079 and #1089

Also, will (hopefully) make it easier in future to add info to workspaces in a backwards compatible way (at least, backwards compatible that the errors will be reasonable when the workspace doesn't load).

### CODE REVIEW

File: src/saveload.c [hunk 1]
```diff
@@ -528,13 +528,26 @@ static void RemoveSaveIndex( Bag bag)
   LINK_BAG(bag) = bag;
 }
 
+
+
+static Char * GetKernelDescription( void )
+{
+    static Char SyKernelDescription[256];
+    strcpy(SyKernelDescription, SyKernelVersion);
+    if(SyUseReadline)
```
Comment (fingolfin) [inline src/saveload.c]: clang-format? add issue labels?

Perhaps we can setup a bot to point this out automatically, it's a bit tiresome. Alternatively, we can also agree to not bother about clang-format anymore, and just let everybody format whichever way they feel like?

Comment (ChrisJefferson) [reply src/saveload.c]: Id be happy with a bot. Maybe i can write a git script to run on my own machine that clangformats bevore each commit. (I actually do use formst on save on other projects i work on, but that reformats the whole file, so is no good for gap).

Comment (ChrisJefferson) [reply src/saveload.c]: Now reformatted
